#!/bin/sh
BASEDIR=`dirname $0`
exec java \
	-Xdock:name=ConResAnalyzer \
	-Xdock:icon=$BASEDIR/../Resources/ConResAnalyzer.icns \
	-Xms512m -Xmx2048m \
	-classpath $BASEDIR/java/ConResAnalyzer.jar:$BASEDIR \
	-Dapple.laf.useScreenMenuBar=true \
	com.grasppe.conres.analyzer.ConResAnalyzerMain
